import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css';
import { useRouter } from 'next/router';


// import NavGallery from "./components/navGallery/page";
//import baseBouton from "./components/baseBouton/page";
import Footer from "./components/footer"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function Layout({ children }) {
//   const router = useRouter();


// }

export default function RootLayout({
  
  children,
  
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<>
    <html lang="fr">
      <head></head>
       <body className={'${inter.className} justify-start'}>
        <main>
          zina1
          <header>
          <section>
          <nav className="bg-grey rounded-lg dark:bg-gray-900 m-2">
         
            <h1 className="bg-white rounded-lg">ici futur Nav</h1>
          </nav>
          </section>
          </header>
       
            <div className="min-h-screen">
               {children}
              </div> 
         
    </main>
          <Footer/>
         </body>
       
    </html> 
    
    </>
  );
}
