import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import { Oswald }  from "next/font/google";
import './globals.css';



// import NavGallery from "./components/navGallery/page";
//import baseBouton from "./components/baseBouton/page";
import Footer from "./components/footer"
// import NavGallery from "./components/navGallery";


const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ["300", "500", "400", "700"] });
const oswald = Oswald({ subsets: ["latin"], weight: ["300", "500", "400", "600"] });

export const metadata: Metadata = {
  title: "GalleryArtiste",
  description: "Generated by create next app",
};

// export default function Layout({ children }) {
//   const router = useRouter();


// }

export default function RootLayout({
  
  children,
  
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<>
    <html lang="fr">
      <head></head>
       <body className={'${inter.className}, ${roboto.className}, ${oswald.className} justify-start'}>
        <main>
          zina1
          {/* <header>
          <section>
           
          {/* <nav className="bg-grey rounded-lg dark:bg-gray-900 m-2">
         
            <h1 className="bg-white rounded-lg">ici futur Nav</h1> */}
          {/* </nav> */}
          {/* </section>
          </header> */} 
       
            <div className="min-h-screen">
               {children}
              </div> 
         
    </main>
          <Footer/>
         </body>
       
    </html> 
    
    </>
  );
}
