import Sidebar from "../components/sidebar"
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Footer from '../components/footer'
// import '@/app/components/footer';




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  

export default function Layout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        
         <div className={`${inter.className} flex items-start justify-between`}>
            <Sidebar/>
          {/* ici width et height en auto pour la gestion d'espace entra la side barre sur le coté droit
          et la gallery placée sur le côté gauche */}
            <div className="w-auto h-auto">
         {children}
          
          </div>
          </div>
                
        
      );
    }
    
        

  