import Sidebar from "../components/sidebar"
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Footer from '../components/footer'
// import '@/app/components/footer';




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  

export default function toutelesgalleryLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <html lang="fr">
          <body className={`${inter.className} flex items-start justify-between`}>
            <Sidebar/>
          {/* ici xidth et height en auto pour la gestion d'espace entra la side barre sur le coté droit
          et la gallery placée sur le côté gauche */}
            <main className="w-auto h-auto">
         
            </main>
          {children}
          {/* <section>
              <Footer/>
          </section> */}
          
             </body>  
                
        </html>
      );
    }
    
        

  